# Generated by Django 3.0.5 on 2020-05-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('item_type', models.CharField(blank=True, choices=[('Starters', 'Starters'), ('Main Courses', 'Main Course'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages')], max_length=50, null=True)),
                ('serviceable', models.CharField(choices=[('Service Available', 'Service Available'), ('Service Not Available', 'Service Not Available')], default='Service Available', max_length=30)),
                ('veg', models.CharField(choices=[('Veg', 'Veg'), ('Non-veg', 'Non-Veg')], default='Veg', max_length=100)),
                ('cuisine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='gallery/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('reviews', models.TextField(max_length=400, null=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodItems.FoodItem')),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
            ],
        ),
    ]
