# Generated by Django 3.0.5 on 2020-05-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodItems', '0002_auto_20200526_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='item_type',
            field=models.CharField(blank=True, choices=[('Starters', 'Starters'), ('Main Courses', 'Main Course'), ('Desserts', 'Desserts'), ('Beverages', 'Beverages')], max_length=50, null=True),
        ),
    ]
