# Generated by Django 3.0.5 on 2020-05-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodItems', '0003_auto_20200526_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
