# Generated by Django 3.0.6 on 2020-05-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='deliveryagent',
            name='username',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='username',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.User'),
        ),
    ]
