# Generated by Django 3.0.5 on 2020-05-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200520_1448'),
        ('accounts', '0002_auto_20200521_2209'),
    ]

    operations = [
    ]
