# Generated by Django 3.0.5 on 2020-05-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20200522_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='res_pics/'),
        ),
    ]
