# Generated by Django 3.0.5 on 2020-05-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_restaurant_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='res_pics/'),
        ),
    ]
