# Generated by Django 3.0.6 on 2020-05-24 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_rating',
            field=models.CharField(default='None', max_length=1),
        ),
        migrations.AddField(
            model_name='order',
            name='rating_description',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_rating',
            field=models.CharField(default='None', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 15, 2, 43, 498534)),
        ),
    ]
