# Generated by Django 3.0.6 on 2020-05-24 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200524_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_rating',
            field=models.CharField(default='None', max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 15, 39, 22, 465725)),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant_rating',
            field=models.CharField(default='None', max_length=6),
        ),
    ]
