# Generated by Django 3.0.5 on 2020-05-27 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200526_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_rating',
            field=models.CharField(default='None', max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='rating_description',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_rating',
            field=models.CharField(default='None', max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 13, 33, 45, 687609)),
        ),
    ]
